@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY5Njg4NjkyLCJpYXQiOjE3Njk2ODUwOTIsImp0aSI6ImY5YzE2ZTUxODdmNTQzNWQ4YzY1ZDNmNGUxYTQ0MzIwIiwidXNlcl9pZCI6IjUifQ.TxYUAGHVe9mvrd-0uNsel4KhwY0GH-LX0t7iOO7pnk4
### Register
POST http://127.0.0.1:8000/api/auth/register/
Content-Type: application/json

{
  "username": "p1",
  "password": "123456",
  "phone": "+48 111 222 333"
}

### JWT Token
POST http://127.0.0.1:8000/api/auth/token/
Content-Type: application/json

{
  "username": "p1",
  "password": "123456",
  "phone": "+48 222 333 444"
}

### Doctors
GET http://127.0.0.1:8000/api/doctors/
Authorization: Bearer {{access_token}}

### Create appointment
POST http://127.0.0.1:8000/api/appointments/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "doctor_id": 3,
  "scheduled_at": "2026-01-29T12:00:00Z",
  "reason": "First visit"
}

### Create appointment
POST http://127.0.0.1:8000/api/appointments/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "doctor_id": 3,
  "scheduled_at": "2026-01-29T19:00:00Z",
  "reason": "First visit"
}

### Create appointment (new)
POST http://127.0.0.1:8000/api/appointments/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "doctor_id": 3,
  "scheduled_at": "2026-01-29T13:00:00Z",
  "reason": "Cancel test"
}

### My appointments
GET http://127.0.0.1:8000/api/appointments/
Authorization: Bearer {{access_token}}

### Cancel appointment
PATCH http://127.0.0.1:8000/api/appointments/3/cancel/
Authorization: Bearer {{access_token}}

### Me (вставь access токен ниже)
GET http://127.0.0.1:8000/api/me/
Authorization: Bearer {{access_token}}
